/* Generated By:JJTree: Do not edit this line. ASTAndExpression.java */

package softtest.ast.java;

public class ASTAndExpression extends ExpressionBase {
    public ASTAndExpression(int id) {
        super(id);
    }

    public ASTAndExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
